[project]
name = "YOURPROJECTNAME"
version = "0.0.0"
description = "YOURPROJECTDESCRIPTION"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "isort>=7.0.0",
    "rich>=14.2.0",
    "toml>=0.10.2",
]
